config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#new'

  resources :users, only: [:show, :get] do
    member do
      get 'show'
    end
  end

  resources :diary, only: [:new, :create]

  resources :objective, only: [:index, :new, :create] do
    resources :amount, only: [:new, :create]
      post 'create'
  end

end

app/models/amount.rb
class Amount < ApplicationRecord
  belongs_to :objectives
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diaries_objective.rb
class DiariesObjective < ApplicationRecord
  belongs_to :diary
  belongs_to :objective
end

app/models/diary.rb
class Diary < ApplicationRecord
  has_many :diaries_objectives
  has_many :objectives, through: :diaries_objectives
  belongs_to :user
end

app/models/objective.rb
class Objective < ApplicationRecord
  has_many :diaries_objectives
  has_many :diaries, through: :diaries_objectives
  has_many :amounts
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :diaries
  has_many :objectives
end

app/controllers/amount_controller.rb
class AmountController < ApplicationController
  def new
    @objectives = Objective.all.where(user_id: current_user.id)
    @amount = Amount.new
  end

  def create
    Amount.create(amount_params)
    redirect_to user_path
  end

  private
  def amount_params
    # params.require(:amount).permit(:amount, :objective_id)
    params.require(:amount).permit(:amount).merge(objective_id: @objectives.id)
  end
end

app/controllers/amounts_controller.rb
class AmountsController < ApplicationController
  def new
    @objectives = Objective.all.where(user_id: current_user.id)
    @amount = Amount.new
  end

  def create
    Amount.create(amount_params)
    redirect_to user_path
  end

  private
  def amount_params
    # params.require(:amount).permit(:amount, :objective_id)
    params.require(:amount).permit(:amount).merge(objective_id: @objectives.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
end

app/controllers/objective_controller.rb
class ObjectivesController < ApplicationController
  def new
    @objective = Objective.new
  end

  def create
    Objective.create(post_params)
    @user = current_user.id
    redirect_to user_path(@user)
  end

  private
  def post_params
    params.require(:objective).permit(:aim, :unit).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = current_user.id
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
    @objectives = Objective.all.where(user_id: current_user.id)
  end

  def delete
    redirect_to new_user_session_path
  end
end

app/helpers/amount_helper.rb
module AmountHelper
end

app/helpers/amounts_helper.rb
module AmountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/amount/new.html.haml
.amount-body
  .amount-body__field
    .amount-body__field__title
      記録の投稿
    .amount-body__field__results
      .amount-body__field__results__top
        本日の成果
      = form_with(model: @amount, url: objective_create_path, multipart: true, local: true)do |form|
        .amount-body__field__results__aims
          .amount-body__field__results__aims__aim
            - @objectives.each do |objective|
              = objective.aim
              = form.number_field :amount
              = objective.unit
              = form.hidden_field :objective_id, :value => @objectives.ids
              %br
          -# .amount-body__field__results__aims__amount
          -#   ※ここに値
          -# .amount-body__field__results__aims__unit
          -#   - @unit.each do |unit|
          -#     = unit.unit
          -#     %br/
        .amount-body__field__results__next
          .amount-body__field__results__next__btn
            = form.submit '次へ'
.footer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GowDiary
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/objectives/new.html.haml
.body
  .body__objective
    .body__objective__head
      目標を設定する
    .body__objective__topic
      ※項目を登録してください
    .body__objective__exsample1
      例）　目標：ジョギング　単位：km
    .body__objective__exsample2
      例）　目標：読書　単位：分
    .body__objective__registration
      = form_with model: @objective, url: objective_index_path, class: :form, local: true do |form|
        = form.text_field :aim, placeholder: :目標, class: :form__title
        = form.text_field :unit, placeholder: :単位, class: :form__text
        = form.submit '登録する', class: :form__btn
.footer

app/views/users/show.html.haml
.body
  .body__mypage
    .body__mypage__head
      .body__mypage__head__title
        = current_user.name + "さんのマイページ"
        .body__mypage__head__account
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
    .body__mypage__create
      .body__mypage__create__diary
        -# = link_to "記録を投稿する", objective_amount_index_path, method: :get, class: 'btn'
        -# .body__mypage__create__diary__notice
        -#   ※目標設定後に投稿可能になります。
      .body__mypage__create__objective
        = link_to "目標を設定する", new_objective_path, method: :get, class: 'btn'
    .body__mypage__body
      .body__mypage__body__diaries
        .body__mypage__body__diaries__topic
          記録一覧
        .body__mypage__body__diaries__diary
          .body__mypage__body__diaries__diary__title
            タイトル
          .body__mypage__body__diaries__diary__date
            2020年9月3日
      .body__mypage__body__info
        .body__mypage__body__info__title
          設定した目標一覧
        .body__mypage__body__info__details
          - @objectives.each do |objective|
            .body__mypage__body__info__details__detail
              = link_to new_objective_amount_path(objective.id) do
                - objective.aim + "の記録を追加"
.footer
  gow-diary